### PR TITLE
add type-specific vil.load functions, remove generic-looking vil.load

### PR DESCRIPTION
**Pull request by decrispell**
@andyneff Are you okay with removing the generic-looking vil.load(), since it actually only works for byte images?

### CODE REVIEW

**Comment by andyneff** [comment]
I understand how you could want to want to force a cast to specific type, and how that exposes it, but I think we should have a "generic" load the native type and give me that (in addition to the explicitly cast ones you have). Otherwise how do I know the native type to say load it?

If I read the old code right, it looks like it was not generic, but was unsigned short int, so 👎 

So I'm not sure if there's a better way to do it, but here's how I could see you writing a truely generic load

1) Call vil_load, and get the base pointer.
2) In the wrapper, start dynamic casting all the different types (https://stackoverflow.com/a/2355220/4166604) Now we know if it natively was float or short int,. etc... 
3) On the python side, we get both the base ptr and type (an enum or string or whatever). And then convert it to the appropriate one there.

The final function API I think would look best is

```python
def vil_load(filename, type=None):
```

So if type isn't specified, it uses native, else it explicitly casts it to the type you want

Examples:

```python
vil_load("a_float_img.tif") # Results in a float image view
vil_load("a_float_img.tif", "double") # Results in a double image view
vil_load("a_double_img.tif", "double") # Results in a double image view
```

So where does the python side of all this go? Well thanks to #36, we have a convenient place for that!

Right now the `CMakeList,txt` just created empty `__init__.py` files. Instead, you will create a __init__.py file in the `vil` directory, put the following code in there (assuming you rename `load` to `_load` in the pybind wrapping): 

```python
from ._vil import *

def load(filename, vil_type=None):
  base_ptr, _vil_type = _load(filename)
  if vil_type is None:
    vil_type = _vil_type
  
  if vil_type == "double":
    return convert_to_double(base_ptr)
  elif vil_type == "fload":
    etc...
```

Maybe there's a much easier C++ trick to do this, but I think this is a complete solution if there is not.

@drewgilliam Seem reasonable?

**Comment by decrispell** [comment]
I'd prefer to keep the python binding code as simple as possible, and also as closely aligned to vxl's c++ interface as possible.  VXL already has a means to load a type-agnostic image, which is to assign the output of vil_load() to a ```vil_image_view_base_sptr```.  Then when you want to actually use the image data, you have to cast it to a ```vil_image_view<T>```.  The wrappers I proposed do the loading and casting in one operation.  How about leaving the generic ```vil.load()``` binding, but have it return a ```vil_image_view_base_sptr```?  The ```vil.image_view_*``` constructors could then take the base class as an argument, just like in vxl proper.

**Comment by decrispell** [comment]
Note that my proposal above still does not support the use case of "I want a vil_image_view of whatever the native pixel type is".  If that's something that we really want to support, your proposal sounds good to me.  I don't see another way to support that use case that doesn't involve the extra complexity of pure python code "wrapping the wrapper".

**Comment by drewgilliam** [comment]
Given "please load the image in its native pixel type" is perhaps the most common method of loading an image across all image loaders, that's what I'd like to see.  In python, I don't generally know what pixel type an image is until I load it.

**Comment by andyneff** [comment]
I understand the need to keep things "as simple as possible" and "as close to c++ as possible" but cases like this base class is just an example where we can see `C++ != python`, which is ok.

I think in this case, it makes sense to diverge from the literal "This is how c++ did it" way to make the python bindings more _user_ friendly

**Note**: Any functions we write in the `__init__.py` file should have a doc string to explain what is is, how to use it, etc... We use the numpy napolean sphinx pattern. [Here is the documentation style we will be using](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy).

**Comment by decrispell** [comment]
Okay, fair enough.  I think most functions we've wrapped so far need a vil_image_view<T> of a specific T as input, but I can imagine that at some point we could have some overloaded functions that take multiple varieties, and we might not need to care what type the image we've loaded actually is.   I'll close this PR.

**Pull request closed without merging**
