### PR TITLE
vgl_pointset_3d numpy

### PR DESCRIPTION
**Pull request by NoahRJohnson**
vgl_pointset_3d support for numpy conversion. def_buffer doesn't work, use as_array instead.

### CODE REVIEW

**Comment by decrispell** [comment]
I'm probably missing some context for this - Why are you trying to squash the points, normals, and a scalar into a single numpy array?

**Comment by NoahRJohnson** [comment]
> I'm probably missing some context for this - Why are you trying to squash the points, normals, and a scalar into a single numpy array?

It has come up in Terra 3D that we often want to operate on a Nx3 numpy array point cloud, and then convert it into a vgl pointset for C++ computation. Once we've done that, we want to convert it back into a numpy array to then save to disk as a binary .npy file.

**Comment by decrispell** [comment]
I see. Mashing them together into a single array seems error-prone to me, but if you're going to do it the code looks fine to me.  

BTW, if your main motivation is saving it as a single numpy file, You could always use the .npz format, and keep the components separate - e.g. ```np.savez(filename, points=points, normals=normals, scalars=scalars) ```

**Comment by drewgilliam** [comment]
I agree with @decrispell - squishing everything into a single matrix seems error prone. 

I'd also think a new vgl_io_pointset_3d function added to vxl if the motivation is saving to file.  That would have the added benefit of getting a pickle function for free.

**Comment by NoahRJohnson** [comment]
VXL PR #809 will add VSL support to vgl_pointset_3d. I've updated this PR with pickle support, which will allow dumping and loading to/from a file.

I'd still like to be able to construct a pointset directly from a numpy array, for efficiency and cleanliness. Can one of you clarify what you mean by error-prone? The conversion seems well-defined to me, based on the number of columns. If this design isn't acceptable, how should I change it?

**Comment by drewgilliam** [comment]
If I hand you a 7-band 3D numpy array, it is hard for a user to know which bands are points, normals, and scalars without diving into the pyvxl code    Dan's comments point to another possibility where you save the points, normals, and scalars as three different numpy arrays that are more easily understood.

**Comment by NoahRJohnson** [comment]
Ok, so you're saying that adding direct 4, 5, and 7 band support introduces a new leaky abstraction interface which requires the user to know the implementation. Then how about I mimic the existing constructors, with multiple buffers? So you could construct with up to three numpy arrays, one each for points, normals, and scalars.

As for the np.savez approach, that will work if I have three numpy arrays I want to save. But accessing the points() method gives you back a list of vgl_point_3d objects, not an array. In practice since I just have a pointset that I want to save, I'll use pickle.dump.

**Comment by decrispell** [comment]
Constructing from multiple numpy arrays seems reasonable to me.

Using pickle to save seems reasonable as well.  I don't really understand the connection between the two (constructing from numpy arrays and saving/loading via pickle) but that's okay.

BTW, as long as ```vgl_point_3d``` is "array like" (implements ```__len__``` and ```___getitem___``` ?) , I believe saving lists of them with numpy would work just fine - it will interpret lists of ```vgl_point_3d```s as 2D arrays.  But that's probably beside the point.

**Comment by NoahRJohnson** [comment]
I didn't realize that about lists of vgl_point_3d - that's cool!

I've updated this PR with the new buffer constructors, which match the existing construction API. What do you think?

**Review by decrispell — APPROVED** [review]

**Pull request merged**
